import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/components/data-table.css"

import { Toaster } from "@/components/ui/sonner"
import { ThemeProvider } from "@/components/theme-provider";
import ThemeScript from "@/components/theme-script";
import { UserProvider } from "@/contexts/UserContext";
import { LoadingProvider } from "@/contexts/LoadingContext";
import { IPOProvider } from "@/contexts/IPOContext";
import Loading from "./loading";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PESB",
  description: "Generated by PESB",
  // manifest: '/manifest.json',
  // themeColor: '#000000',
  icons: [
    {
      rel: 'icon',
      url: '/favicon.png',
    },
    {
      rel: 'apple-touch-icon',
      url: '/apple-touch-icon.png',
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const GA_TRACKING_ID = process.env.NEXT_PUBLIC_GA_TRACKING_ID;


  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* <link rel="manifest" href="/manifest.json" /> */}

        <ThemeScript />


      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* <SidebarProvider > */}
          <IPOProvider>
            <UserProvider>
              <LoadingProvider>
                {children}
                <Loading />
              </LoadingProvider>
            </UserProvider>
          </IPOProvider>
          <Toaster position="top-center" />
          {/* </SidebarProvider> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
